pipeline:
- name: ingest_promql
- name: feature_extraction_tsfel
  follows: [ingest_promql]
- name: generate_insights
  follows: [feature_extraction_tsfel]
- name: config_generator_otel_processor
  follows: [feature_extraction_tsfel, generate_insights]
parameters:
- name: ingest_promql
  type: ingest
  subtype: promql
  input_data: []
  output_data: [signals]
  config:
    url: 'http://thanos_query:19192'
    ingest_window: '15m'
    filter_metadata: "app_|cluster_|k8s_|nwdaf|process_"
    ingest_name_template: "$count|$__name__($app,$cluster,$instance,$processor,$IP)"
- name: feature_extraction_tsfel
  type: extract
  subtype: tsfel
  input_data: [signals]
  output_data: [extracted_signals]
  config:
    sampling_frequency: 0.0333
    resample_rate: "5s"
    features_json_file: "extract/tsfel_conf/limited_features.json"
- name: generate_insights
  type: insights
  subtype:
  input_data: [extracted_signals]
  output_data: [signals_to_keep, signals_to_reduce, text_insights]
  config:
    analysis_chain:
    - type: zero_values
    - type: fixed_values
      filter_signals_by_tags: ["zero_values"]
    - type: monotonic
      filter_signals_by_tags: ["zero_values","fixed_values"]
- name: config_generator_otel_processor
  type: config_generator
  subtype: otel_processor
  input_data: [extracted_signals, signals_to_keep, signals_to_reduce]
  output_data: [r_value]
  config:
    signal_filter_template: "k8s_|nwdaf_|process_"
    signal_name_template: "$original_name"
    signal_condition_template: "resource.attributes[\"processor\"] == \"$processor\" and resource.attributes[\"instance\"] == \"$instance\""
    processor_id_template: "$processor"
    monotonic_freq_interval: 30s
    metrics_frequency:
    - name: process_cpu_seconds_total
      interval: 20s
    - name: k8s_pod_network_bytes
      interval: 10s
    directory: /tmp
    url: http://manager:5010
