name: release - build test and push

on:
  push:
    tags:
      - 'v*.*'

env:
  QUAY_ROBOT_USER: observ-vol-mgt+quay_io_observ_vol_mgt_github_actions_robot

jobs:
  build-test-push:
    permissions:
      contents: write
    name: build-test-push
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"    
    - name: install make
      run: sudo apt-get install make
    - name: checkout
      uses: actions/checkout@v4
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Print release version
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: login to quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ env.QUAY_ROBOT_USER }}
        password: ${{ secrets.QUAY_SECRET }}
    - name: Update project level docs
      run: |
          VERSION=${{ env.RELEASE_VERSION }} make ci_push
    - name: run controller tests
      run: |
          cd controller
          VERSION=${{ env.RELEASE_VERSION }} make ci_push
    - name: push manager configurator image
      run: |
          cd manager/configurator
          VERSION=${{ env.RELEASE_VERSION }} make ci_push
    - name: push manager alermanager image
      run: |
          cd manager/alertmanager
          VERSION=${{ env.RELEASE_VERSION }} make ci_push
    - name: push processor image
      run: |
          cd processor
          VERSION=${{ env.RELEASE_VERSION }} make ci_push
    - name: push otel-collector-proxy image
      run: |
          cd otel-collector-proxy
          VERSION=${{ env.RELEASE_VERSION }} make ci_push
